### PR TITLE
Time directive

### PR DESCRIPTION
**Pull request by lelamson**

### CODE REVIEW

**Comment by andyjac** [comment]
@lelamson looks good! one quick question: how do we want the time picking for each day to work? do we want seven time pickers on the page or do want there to be someway for her to select the specific day/days she would like to set times for (i.e. a dropdown or check boxes or something)?

**Comment by lelamson** [comment]
@andyjac Any of the following could work:
-Dropdown to set the day (may be easiest to set repeat hours)
-Checkboxes also works in place of dropdown
-Use an accordion like style (cool factor)

**Comment by andyjac** [comment]
@lelamson yeah, i guess we can start trying different things and see which one we like the best. also, sort nit picky, but i noticed the AM/PM buttons are a bit out of alignment.

**Comment by bullitbd** [comment]
Gina had asked in a prior session that she just have a text field she can fill in for each day, rather than all the dropdowns and buttons.  I spoke with her today about that, and she put her wishes this way:

1. If we can use google places web api (which I successfully used) she would prefer that - then she doesn't have to keep following up on restaurant hours, etc.
2. If not, she'd just like the text fields for each day.

Google places has a free limit of 1000 requests per day - I propose we do the following: run a daily cron request for all the places and update hours (and possibly other things as well...).  I believe we're just sending text strings to Brandon as it is - so no changes needed there, and places returns formatted strings for each weekday including wonky double openings, etc. (along with open and close fields for each day...).

We can show the 7 text fields IF NOT HOURS flag in the data.  Happy to tackle this one if agreed... as well as directive logic - also happy to pretty up the form.

**Comment by andyjac** [comment]
@bullitbd cool, thanks for the info. yeah, if you want to work on that you can coordinate with @lelamson since he's the one who build the timepicker directive. would also love your input as to what we've got build so far. if you pull master and run the server locally and head to `localhost:3000/` you can check it out.

**Comment by bullitbd** [comment]
@andyjac have done so... lotsa work!  I'll dive in further now that I have time.  Are you at cf at all?

**Comment by andyjac** [comment]
@bullitbd awesome! i have been at cf here and there. planning on heading in tomorrow to work a bit on a project i'm doing with kevin. i am usually pretty flexible though, so if you know you're gonna be in let me know and i'll try to come down also!

**Comment by andyjac** [comment]
also @lelamson i'm gonna merge this for now. we can continue working on timepicker stuff in a new branch!

**Comment by bullitbd** [comment]
@andyjac I should be in most of tomorrow...

**Comment by bullitbd** [comment]
@lelamson ...hope your morning went well!

**Comment by andyjac** [comment]
@bullitbd great :)

**Pull request merged**
