### PR TITLE
Basic angular

### PR DESCRIPTION
**Pull request by andyjac**
So, obviously this is super basic, but it's a framework to use for going forward. I removed an old user test that will be irrelevant. 

Also, at some point we will want to talk about routing. You'll remember before that we were using `/hinton` as a starting point for the admin routes. This will obviously change now that we are using angular for routing. I set it to serve our static files from `/`, which would mean our full route would look like: `hinton.herokuapp.com/#/`. Angular routes would then be mounted on top, like `/#/restaurant_form` or something.

### CODE REVIEW

**Comment by andyjac** [comment]
@neagan @lelamson

**Comment by lelamson** [comment]
To bypass the auth route since my DB has no users, I am gonna serve the form page from /angular

**Comment by andyjac** [comment]
a single `/` from the server should be fine. it shouldn't have to go through the auth routes since those are being served from `/hinton`

**Comment by andyjac** [comment]
if you pull this down it should work just the same without asking you to sign in.

**Pull request merged**
